### ISSUE TITLE
LDES Server fail to start from docker-compose up

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDESServer4J#226]
### The Problem
After the `docker compose up` LDES Server fails to start.

GitHub commit tag: [42c25b866e30e8a0ba8473796a21ac87456e3dd1](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/42c25b866e30e8a0ba8473796a21ac87456e3dd1)
### Error log
```
unexpected character "-" in variable name near "spring_data_mongodb_auto-index-creation=True\nspring_main_allow-bean-definition-overriding=True\n\n"
```

The error also exists on docker tag: [20220914T0740](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pkgs/container/ldes-server/41628349?tag=20220914T0740)
### Error log
```
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[ldes-server-application.jar:na]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) ~[ldes-server-application.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fragmentationService' defined in class path resource [be/vlaanderen/informatievlaanderen/ldes/server/domain/config/FragmentationStrategyConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'fragmentationService' threw exception; nested exception is java.lang.NumberFormatException: For input string: ""
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        ... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'fragmentationService' threw exception; nested exception is java.lang.NumberFormatException: For input string: ""
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.22]
        ... 41 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[na:na]
        at java.base/java.lang.Long.parseLong(Long.java:721) ~[na:na]
        at java.base/java.lang.Long.valueOf(Long.java:1159) ~[na:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.fragme
```

**Comment by zargha** [comment]
Tested with `docker-compose` instead of docker desktop and using correct env variables.
Tested with Docker image tag `20220923t0958`.
