### ISSUE TITLE
ldes server docker container fail

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDESServer4J#318]
ldes server docker container fails to build.

GitHub commit: [da80fb577a0f2f7f7ac28b20ebbed8510de520ec](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/da80fb577a0f2f7f7ac28b20ebbed8510de520ec)

Docker image tag: [20221121T1401](https://github.com/orgs/Informatievlaanderen/packages/container/ldes-server/52016979?tag=20221121T1401)

Error log:
```
s": {"type": "Linux", "name": "Linux", "architecture": "amd64", "version": "5.15.49-linuxkit"}, "platform": "Java/Oracle Corporation/18-ea+11"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=null, streamFactoryFactory=null, commandListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListener@47a4eee2, org.springframework.cloud.sleuth.instrument.mongodb.TraceMongoCommandListener@6889f56f], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.Jep395RecordCodecProvider@231b35fb]}, clusterSettings={hosts=[ldes.mongodb:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='30000 ms', localThreshold='30000 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, sendBufferSize=0}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, sendBufferSize=0}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener@18709cb2], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=JAVA_LEGACY, serverApi=null, autoEncryptionSettings=null, contextProvider=org.springframework.cloud.sleuth.instrument.mongodb.TraceSynchronousMongoClientSettingsBuilderCustomizer$$Lambda$830/0x00000008010a5830@26da1ba2}
2022-12-01 13:06:58.503  INFO [,,] 1 --- [s.mongodb:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:1}] to ldes.mongodb:27017
2022-12-01 13:06:58.504  INFO [,,] 1 --- [s.mongodb:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:2}] to ldes.mongodb:27017
2022-12-01 13:06:58.514  INFO [,,] 1 --- [s.mongodb:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=ldes.mongodb:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=17, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=59204805}
2022-12-01 13:07:00.675  INFO [,,] 1 --- [           main] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:3, serverValue:3}] to ldes.mongodb:27017
2022-12-01 13:07:01.997  WARN [,,] 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'treeNodeRemoverImpl' defined in URL [jar:file:/lib/ldes-fragmentisers-geospatial-jar-with-dependencies.jar!/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/TreeNodeRemoverImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retentionPolicyMap' defined in class path resource [be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/RetentionPolicyConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'retentionPolicyMap' threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.valueobjects.ViewSpecification.getRetentionConfigs()" is null
2022-12-01 13:07:02.038  INFO [,,] 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-12-01 13:07:02.061  WARN [,,] 1 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [BufferPoolPruner-1-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@18-ea/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@18-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@18-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
 java.base@18-ea/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@18-ea/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@18-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@18-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@18-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@18-ea/java.lang.Thread.run(Thread.java:833)
2022-12-01 13:07:02.121  INFO [,,] 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-12-01 13:07:02.163 ERROR [,,] 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'treeNodeRemoverImpl' defined in URL [jar:file:/lib/ldes-fragmentisers-geospatial-jar-with-dependencies.jar!/be/vlaanderen/informatievlaanderen/ldes/server/domain/ldesfragment/services/TreeNodeRemoverImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retentionPolicyMap' defined in class path resource [be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/RetentionPolicyConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'retentionPolicyMap' threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.valueobjects.ViewSpecification.getRetentionConfigs()" is null
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:2.7.5]
        at be.vlaanderen.informatievlaanderen.ldes.server.Application.main(Application.java:9) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[ldes-server-application.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[ldes-server-application.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[ldes-server-application.jar:na]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) ~[ldes-server-application.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retentionPolicyMap' defined in class path resource [be/vlaanderen/informatievlaanderen/ldes/server/domain/ldes/retentionpolicy/RetentionPolicyConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'retentionPolicyMap' threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.valueobjects.ViewSpecification.getRetentionConfigs()" is null
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        ... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.Map]: Factory method 'retentionPolicyMap' threw exception; nested exception is java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.valueobjects.ViewSpecification.getRetentionConfigs()" is null
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        ... 41 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "be.vlaanderen.informatievlaanderen.ldes.server.domain.viewcreation.valueobjects.ViewSpecification.getRetentionConfigs()" is null
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.ldes.retentionpolicy.RetentionPolicyConfig.lambda$retentionPolicyMap$0(RetentionPolicyConfig.java:32) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[na:na]
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.ldes.retentionpolicy.RetentionPolicyConfig.retentionPolicyMap(RetentionPolicyConfig.java:29) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.ldes.retentionpolicy.RetentionPolicyConfig$$EnhancerBySpringCGLIB$$48df6807.CGLIB$retentionPolicyMap$0(<generated>) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.ldes.retentionpolicy.RetentionPolicyConfig$$EnhancerBySpringCGLIB$$48df6807$$FastClassBySpringCGLIB$$e41eb1e8.invoke(<generated>) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        at be.vlaanderen.informatievlaanderen.ldes.server.domain.ldes.retentionpolicy.RetentionPolicyConfig$$EnhancerBySpringCGLIB$$48df6807.retentionPolicyMap(<generated>) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[ldes-fragmentisers-geospatial-jar-with-dependencies.jar:5.3.23]
        ... 42 common frames omitted
```

**Comment by zargha** [comment]
tested with latest tags. issue solved.
